version: '2'
services:
  datastore:
    image: busybox
    volumes:
      - /share
      - ./volums/mysql/volumes:/var/lib/mysql
      - ./volums/redis_data:/data
  rails:
    container_name: rails
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    command: bundle exec unicorn -p 3000 -c ./config/unicorn.rb
    ports:
      - '3000:3000'
    environment:
      RAILS_ENV: development
      MYSQL_ROOT_PASSWORD: 'root'
      DATABASE_URL: 'mysql2://root:root@db:3306'
    depends_on:
      - db
    volumes:
      - ./:/app
    volumes_from:
      - datastore
    depends_on:
      - datastore
      - db
    links:
      - db
      - redis
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - '80:80'
    volumes_from:
      - datastore
    depends_on:
      - datastore
  db:
    user: "1000:50"
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "3306:3306"
    volumes_from:
      - datastore
    depends_on:
      - datastore
    environment:
      MYSQL_ROOT_PASSWORD: root
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes_from:
      - datastore
